### ISSUE TITLE
TODO - curto prazo

### ISSUE THREAD

**Issue by Duarte0903** [FSUMinho/website#1]
- [x] Trocar o roadmap para slick slider ***(ou eliminar)***
- [x] Colocar os patrocinadores no tier correto
- [x] Deixar o ***footer*** mais responsivo 
- [x] Ligar os news-cards a um post no instagram ***(com a API??)*** ***(ligados sem API)***
- [x] Adicionar mais conteúdo ás páginas dos setores
- [x] Guardar a linguagem na cache do browser ***(se possível)***
- [x] Melhorar formulário de contacto
